name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix: 
        ruby: [ '2.6', '2.7', '3.0', '3.1']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v3
        with:
          ruby-version:  ${{ matrix.ruby }}
      - name: Install Bundler
        run: gem install bundler
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake spec
